# Generated by Django 5.0.1 on 2024-05-25 05:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=30)),
                ('numero_telefonico', models.CharField(max_length=13)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('numero_visitas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClienteFrecuente',
            fields=[
                ('id_cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mi_app.cliente')),
                ('preferencias_comidas', models.CharField(max_length=40)),
                ('preferencias_mesa', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_comensales', models.PositiveIntegerField()),
                ('fecha_hora_reserva', models.DateTimeField()),
                ('tipo_reserva', models.CharField(max_length=30)),
                ('tiempo_estancia_estimado', models.DurationField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPagos',
            fields=[
                ('id_registropagos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=10)),
                ('id_reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.reservacion')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioCalificacion',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(max_length=1000)),
                ('calificacion', models.PositiveIntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.cliente')),
                ('id_reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.reservacion')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialReservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_visita', models.DateTimeField()),
                ('detalles_reservacion', models.TextField(max_length=1000)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.cliente')),
                ('id_reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.reservacion')),
            ],
            options={
                'unique_together': {('id_reservacion', 'id_cliente')},
            },
        ),
    ]
