# Generated by Django 5.0.6 on 2024-05-25 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='id_mesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mi_app.mesa'),
        ),
    ]
