# Generated by Django 5.0.6 on 2024-05-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_reservacion_id_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_visitas',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
